version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123qweloL
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:123qweloL@db:5432/postgres
    ports:
      - "8000:8000"
    volumes:
      - ./boom_integration:/app/boom_integration
      - ./yolo11n.pt:/app/yolo11n.pt

volumes:
  pgdata: 